### ISSUE TITLE
Latest SushiLite release and OJS 3.2.1-1 issue

### ISSUE THREAD

**Issue by paulo-graca** [ulsdevteam/ojs-sushiLite-plugin#5]
I'm getting this error when trying to use this plugin with `ojs 3.2.1-1`:

```
Fatal error: Uncaught Error: Using $this when not in object context in /ojs/ojs-3.2.1-1/lib/pkp/classes/core/PKPRequest.inc.php:698 Stack trace: #0 /ojs/ojs-3.2.1-1/plugins/generic/sushiLite/pages/SushiLiteHandler.inc.php(32): PKPRequest::getRequestedOp(Object(Request)) #1 /ojs/ojs-3.2.1-1/lib/pkp/classes/core/PKPRouter.inc.php(391): SushiLiteHandler->index(Array, Object(Request)) #2 /ojs/ojs-3.2.1-1/lib/pkp/classes/core/PKPPageRouter.inc.php(231): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false) #3 /ojs/ojs-3.2.1-1/lib/pkp/classes/core/Dispatcher.inc.php(143): PKPPageRouter->route(Object(Request)) #4 /ojs/ojs-3.2.1-1/lib/pkp/classes/core/PKPApplication.inc.php(279): Dispatcher->dispatch(Object(Request)) #5 /ojs/ojs-3.2.1-1/index.php(68): PKPApplication->execute() #6 {main} thrown in /ojs/ojs-3.2.1-1/lib/pkp/classes/core/PKPRequest.inc.php on line 698
```

**Comment by ctgraham** [comment]
@paulo-graca, please try this new release to confirm this is fixed:
https://github.com/ulsdevteam/ojs-sushiLite-plugin/releases/tag/v1.1.2-0
